// <auto-generated />
namespace ClaimManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addednewpropertiesforaspnetusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewpropertiesforaspnetusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201605052338274_addednewpropertiesforaspnetusers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
